name: project_nxt_professional
description: "Project-Nxt for Professional"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.3
  easy_localization: ^3.0.7
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  dio: ^5.5.0+1
  shared_preferences: ^2.2.3
  get_it: ^7.6.7
  dartz: ^0.10.1
  intl_phone_field: ^3.2.0
  socket_io_client: ^2.0.3+1
  url_launcher: ^6.2.4
  google_fonts: ^5.1.0
  #  cached_video_player: ^2.0.2
  #  video_player: ^2.4.7
  carousel_slider: ^4.2.1
  in_app_purchase: ^3.1.13
  timeago: ^3.7.0
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  expandable: ^5.0.1
  flutter_expanded_tile: ^0.4.0
  better_player: ^0.0.84
  auto_orientation: ^2.3.1
  webview_flutter: ^4.8.0
  path: ^1.9.0
  mime: ^1.0.6
  file_picker: ^8.1.2
  pretty_qr_code: ^3.3.0
  screenshot: ^3.0.0
  syncfusion_flutter_pdf: ^27.1.52
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  #  image_gallery_saver: ^2.0.3
  cached_network_image: ^3.4.1
  toggle_list: ^0.3.1
  auto_size_text: ^3.0.0
  percent_indicator: ^4.2.3
  story_view: ^0.16.5
  badges: ^3.1.2
  flutter_linkify: ^6.0.0
  skeletonizer: ^1.4.2
  country_code_picker: ^3.1.0
  country_picker_pro: ^0.0.5
  firebase_core: ^3.6.0
  stream_chat_flutter: ^8.0.0-beta.3
  firebase_messaging: ^15.1.3
  awesome_notifications: ^0.10.0
  flutter_chat_ui: ^1.6.12
  easy_image_viewer: ^1.5.1
  dropdown_button2: ^2.3.9
  video_player: ^2.9.2
  flutter_spinkit: ^5.2.1
  transparent_image: ^2.0.1
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/appearance/
    - assets/fonts/
    - assets/translation/

  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf

    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: Montserrat-SemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf

    - family: Inter-Bold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf

    - family: Inter-Medium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf

    - family: BebasNeue-Book
      fonts:
        - asset: assets/fonts/BebasNeue-Book-Regular.otf